library(shinydashboard)
library(ggplot2)
library(shiny)
library(reticulate)
library(shinyjs)
library(plotly)
library(rjson)
library(tools)
library(DT)
library(gplots)
library(SingleR)
library(shinyBS)
library(RLumShiny)
library("htmltools")
library("bsplus")
source("gui/ui.R")
source("gui/server.R")

options(shiny.host="0.0.0.0")
options(shiny.port=23123)
options(shiny.maxRequestSize=3000*1024^2)

shinyApp(ui, server)
